### ISSUE TITLE
Fatal Exception: java.io.IOException: Invalid key specification: java.security.spec.InvalidKeySpecException: com.google.android.gms.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key

### ISSUE THREAD

**Issue by DanielBarcenas97** [akshaaatt/Google-IAP#65]
Fatal Exception: java.io.IOException: Invalid key specification: java.security.spec.InvalidKeySpecException: com.google.android.gms.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key

**Comment by xyang5987** [comment]
I had the same error on subscription for com.github.akshaaatt:Google-IAP:1.2.5

**Comment by xyang5987** [comment]
Here are the error messages:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx, PID: 17035
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.billing.PURCHASES_UPDATED flg=0x10 pkg=com.xxx.xxxg (has extras) } in com.android.billingclient.api.zzn@34cdefe
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1493)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.io.IOException: Invalid key specification: java.security.spec.InvalidKeySpecException: com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key
        at com.aemerse.iap.Security.generatePublicKey(Security.kt:65)
        at com.aemerse.iap.Security.verifyPurchase(Security.kt:42)
        at com.aemerse.iap.BillingService.isSignatureValid(BillingService.kt:260)
        at com.aemerse.iap.BillingService.processPurchases(BillingService.kt:184)
        at com.aemerse.iap.BillingService.processPurchases$default(BillingService.kt:175)
        at com.aemerse.iap.BillingService.onPurchasesUpdated(BillingService.kt:153)
        at com.android.billingclient.api.zzn.onReceive(com.android.billingclient:billing@@5.0.0:5)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1483)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by xyang5987** [comment]
It's my mistake. I used a wrong public key. Now Google-IAP  works on veryfyPurchase.
